app:
  name: "Live coding test"
  version: "1.0.0"
  environment: "production"

server:
  host: "localhost"
  port: "8080"
  timeout: "30s"
  protocol: http
  api_prefix: "/api"
  api_version: "/v1"

database:
  host: "localhost"
  port: 5432
  username: "devuser"
  password: "devpass"
  name: "live_coding"
  timezone: "Asia/Tehran"
  ssl_mode: "disable"

logging:
  enabled: "true"
  level: "info"
  format: "json"

file:
  user_json: "./users_data.json"

worker:
  user_worker_count: 10