// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"live-coding/config"
	"live-coding/infra"
	"live-coding/internal/shared/adapter/inbound/http"
)

// Injectors from wire.go:

func InitHttp(configConfig config.Config) (Http, func(), error) {
	databaseConfig := provideDatabaseConfig(configConfig)
	txDB, cleanup, err := infra.NewDBWithTX(databaseConfig)
	if err != nil {
		return Http{}, nil, err
	}
	echo, err := infra.NewHttpServer(txDB)
	if err != nil {
		cleanup()
		return Http{}, nil, err
	}
	http := provideHttp(echo)
	return http, func() {
		cleanup()
	}, nil
}

// wire.go:

var inboundSet = wire.NewSet()

var infraSet = wire.NewSet(infra.NewHttpServer, infra.NewDBWithTX, infra.NewRedisClient, provideHttpDependencies,
	provideRunInTransaction,
)

var configSet = wire.NewSet(
	provideHttpServerConfig,
	provideDatabaseConfig,
	provideKafkaConfig,
)

var serviceSet = wire.NewSet()

func provideHttpDependencies(e *echo.Echo, cfg infra.HTTPServerConfig) http.Dependencies {

	return http.Dependencies{
		Echo:        e,
		Middlewares: http.Middlewares{},
		Prefix:      cfg.ApiPrefix + cfg.ApiVersion,
		Debug:       cfg.Debug,
	}
}

func provideDatabaseConfig(cfg config.Config) infra.DatabaseConfig {
	return infra.DatabaseConfig{
		DatabasePort:       cfg.Database.Port,
		DatabaseHost:       cfg.Database.Host,
		DatabaseName:       cfg.Database.Name,
		DatabaseUsername:   cfg.Database.Username,
		DatabasePassword:   cfg.Database.Password,
		DatabaseTimezone:   cfg.Database.Timezone,
		DatabaseSslMode:    cfg.Database.SSLMode,
		DatabaseLogEnabled: cfg.Logging.Enabled,
	}
}

func provideHttpServerConfig(cfg config.Config) infra.HTTPServerConfig {
	return infra.HTTPServerConfig{
		Debug:      cfg.App.Environment == "dev",
		Protocol:   cfg.Server.Protocol,
		Host:       cfg.Server.Host,
		Port:       cfg.Server.Port,
		ApiPrefix:  cfg.Server.ApiPrefix,
		ApiVersion: cfg.Server.ApiVersion,
		LogEnable:  cfg.Logging.Enabled,
	}
}

func provideKafkaConfig(cfg config.Config) config.KafkaConfig {
	return cfg.Kafka
}

func provideRunInTransaction(txDB *infra.TxDB) infra.IRunInTransaction {
	return txDB.RunInTransaction
}

func provideHttp(
	server *echo.Echo,
) Http {
	return newHttp(server)
}
